openapi: 3.0.3
info:
  title: 書籍管理API
  description: 書籍を管理するAPI
  version: 1.0.0
  contact:
    name: Ryoichi Hayashi
servers:
  - url: 'http://localhost:8080'
paths:
  /authors:
    post:
      description: 著者登録
      responses:
        '200':
          description: OK
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthor'
      operationId: createAuthor
      tags:
        - author
components:
  schemas:
    CreateAuthor:
      type: object
      description: 著者作成
      properties:
        name:
          type: string
          description: 著者名
          example: 夏目　漱石
          minLength: 1
          maxLength: 100
        birthday:
          type: string
          description: 誕生日
          example: '2020-01-01'
          format: date
      required:
        - name
tags:
  - name: author
    description: 著者
  - name: book
    description: 書籍
