openapi: 3.0.3
info:
  title: 書籍管理API
  description: 書籍を管理するAPI
  version: 1.0.0
  contact:
    name: Ryoichi Hayashi
servers:
  - url: 'http://localhost:8080'
paths:
  /authors:
    post:
      description: 著者登録
      responses:
        '200':
          description: OK
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthor'
      operationId: createAuthor
      tags:
        - author
      summary: 著者登録
    patch:
      summary: 著者更新
      operationId: updateAuthor
      responses:
        '200':
          description: OK
      description: 著者更新
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthor'
      tags:
        - author
  /books:
    post:
      summary: 書籍登録
      operationId: createBook
      responses:
        '200':
          description: OK
      description: 書籍登録
      tags:
        - book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBook'
    patch:
      summary: 書籍更新
      operationId: updateBook
      responses:
        '200':
          description: OK
      description: 書籍更新
      tags:
        - book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBook'
    get:
      summary: 書籍の検索
      operationId: searchBook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
      tags:
        - book
      description: 書籍の検索
      parameters:
        - schema:
            type: string
            example: こころ
          in: query
          name: bookTitle
          description: 書籍タイトル
        - schema:
            type: string
            example: 夏目　漱石
          in: query
          name: authorName
          description: 著者名
        - schema:
            type: string
            example: 978-4101010137
          in: query
          name: isbn
          description: ISBN
  '/authors/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: ID
    get:
      summary: 著者をIDで取得
      tags:
        - author
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Not Found
      operationId: getAuthorById
      description: 著者をIDで取得
components:
  schemas:
    CreateAuthor:
      type: object
      description: 著者作成
      properties:
        name:
          type: string
          description: 著者名
          example: 夏目　漱石
          minLength: 1
          maxLength: 100
        birthday:
          type: string
          description: 誕生日
          example: '2020-01-01'
          format: date
      required:
        - name
    UpdateAuthor:
      title: UpdateAuthor
      x-stoplight:
        id: ovpwu12xvsbxi
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: ID
        name:
          type: string
          minLength: 1
          maxLength: 100
          example: 夏目　漱石
          description: 著者名
        birthday:
          type: string
          format: date
          example: '2000-01-01'
          description: 誕生日
      required:
        - id
        - name
    CreateBook:
      title: CreateBook
      x-stoplight:
        id: ou5v3o707qcq5
      type: object
      properties:
        isbn:
          type: string
          description: ISBN
          maxLength: 17
          example: 978-4101010137
        authorId:
          type: integer
          example: 1
        title:
          type: string
          description: タイトル
          minLength: 1
          maxLength: 100
          example: こころ
      required:
        - authorId
        - title
    UpdateBook:
      title: UpdateBook
      x-stoplight:
        id: 2i79z2qla5if5
      type: object
      properties:
        id:
          type: integer
          description: ID
        isbn:
          type: string
          description: ISBN
          maxLength: 17
          example: 978-4101010137
        authorId:
          type: integer
          example: 1
        title:
          type: string
          description: タイトル
          minLength: 1
          maxLength: 100
          example: こころ
      required:
        - id
        - authorId
        - title
    Author:
      title: Author
      x-stoplight:
        id: g8akxct1grn56
      type: object
      properties:
        id:
          type: integer
          description: ID
          example: 1
        name:
          type: string
          description: 著者名
          example: 夏目　漱石
        birthday:
          type: string
          description: 誕生日
          example: '2000-01-01'
        books:
          type: array
          items:
            $ref: '#/components/schemas/AuthorBook'
      required:
        - id
        - name
        - books
    AuthorBook:
      title: AuthorBook
      x-stoplight:
        id: 2g0opobb408k1
      type: object
      properties:
        id:
          type: integer
          description: ID
          default: 1
        isbn:
          type: string
          example: 978-4101010137
        title:
          type: string
          example: こころ
      required:
        - id
        - title
      description: ''
    Book:
      title: Book
      x-stoplight:
        id: 1k3jugezay1ke
      type: object
      description: 書籍
      properties:
        id:
          type: integer
          description: ID
          example: '1'
        isbn:
          type: string
          description: ISBN
          example: 978-4101010137
        title:
          type: string
          description: タイトル
          example: こころ
        author:
          $ref: '#/components/schemas/BookAuthor'
      required:
        - id
        - title
        - author
    BookAuthor:
      title: BookAuthor
      x-stoplight:
        id: taweepph9g19d
      type: object
      description: 本の著者
      properties:
        authorId:
          type: integer
          example: 1
          description: ID
        name:
          type: string
          description: 著者名
          example: 夏目　漱石
        birthday:
          type: string
          description: 誕生日
          example: '2000-01-01'
          format: date
      required:
        - authorId
        - name
tags:
  - name: author
    description: 著者
  - name: book
    description: 書籍
